name: Generate Monthly Test Report

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'Name of the workflow to collect artifacts from'
        required: true
        default: 'Run BugBug - BNE Production Suite'

permissions:
  actions: read  # Needed to list and download artifacts
  contents: read  # Required to read repo content

jobs:
  collect-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq and coreutils
        run: sudo apt-get install -y jq coreutils

      - name: List and Download Artifacts from a Specific Workflow (Current Month)
        run: |
          mkdir -p all-test-results
          echo "Fetching artifacts from workflow: '${{ inputs.workflow_name }}' (current month)"

          # Get the first and last day of the current month in UTC
          FIRST_DAY=$(date -u +"%Y-%m-01T00:00:00Z")
          LAST_DAY=$(date -u -d "$(date -u +%Y-%m-01) +1 month -1 day" +"%Y-%m-%dT23:59:59Z")

          echo "Filtering runs between $FIRST_DAY and $LAST_DAY"

          WORKFLOW_ID=$(gh workflow list --json id,name --jq '.[] | select(.name=="${{ inputs.workflow_name }}") | .id' --repo ${{ github.repository }})

          if [ -z "$WORKFLOW_ID" ]; then
            echo "No workflow found with the name '${{ inputs.workflow_name }}'"
            exit 1
          fi

          RUNS=$(gh run list --workflow $WORKFLOW_ID --limit 100 --json databaseId,createdAt,status \
            --jq ".[] | select(.status==\"completed\" and .createdAt >= \"$FIRST_DAY\" and .createdAt <= \"$LAST_DAY\") | .databaseId" \
            --repo ${{ github.repository }})

          if [ -z "$RUNS" ]; then
            echo "No completed workflow runs in the current month."
            exit 0
          fi

          for RUN_ID in $RUNS; do
            echo "Downloading artifacts from workflow run: $RUN_ID"
            gh run download $RUN_ID --dir all-test-results || echo "No artifacts found for $RUN_ID"
          done
          
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install junitparser for Merging JUnit XML
        run: pip install junitparser

      - name: Merge JUnit XML Reports
        run: |
          mkdir -p monthly-results
          python - <<EOF
          from junitparser import JUnitXml, TestSuite, TestCase
      
          merged_xml = JUnitXml()
          merged_suites = TestSuite(name="Merged Test Suites")
      
          import glob
          test_files = glob.glob("all-test-results/**/*.xml", recursive=True)
      
          if not test_files:
              print("No JUnit XML files found to merge.")
              exit(1)
      
          total_tests = 0
          total_failures = 0
          total_errors = 0
          total_skipped = 0
          total_time = 0.0
      
          for file in test_files:
              print(f"Processing: {file}")
              xml = JUnitXml.fromfile(file)
      
              for suite in xml:
                  total_tests += suite.tests
                  total_failures += suite.failures
                  total_errors += suite.errors
                  total_skipped += suite.skipped
                  total_time += float(suite.time) if suite.time else 0.0
                  
                  # Append test cases individually
                  for case in suite:
                      merged_suites.add_testcase(case)
      
          # Set final counts in the merged test suite
          merged_suites.tests = total_tests
          merged_suites.failures = total_failures
          merged_suites.errors = total_errors
          merged_suites.skipped = total_skipped
          merged_suites.time = total_time
      
          merged_xml.add_testsuite(merged_suites)
      
          output_file = "monthly-results/monthly-test-results.xml"
          merged_xml.write(output_file)
          print(f"Merged JUnit XML report saved to: {output_file}")
          EOF
          
      - name: Upload Merged JUnit XML Report
        uses: actions/upload-artifact@v4
        with:
          name: monthly-junit-test-report
          path: monthly-results/monthly-test-results.xml
          retention-days: 30

      - name: Install dependencies
        run: pip install plotly python-docx kaleido      

      - name: Parse JUnit XML and Generate Word Report
        env:
          WORKFLOW_NAME: ${{ github.event.inputs.workflow_name }}
        run: |
          python3 - <<EOF
          import os
          import glob
          import plotly.graph_objects as go
          from junitparser import JUnitXml, Error, Failure, Skipped, TestSuite
          from docx import Document
          from docx.shared import Inches, Pt
      
          XML_DIR = "monthly-results"
          REPORT_NAME = "${{ github.event.inputs.workflow_name }} Test Report"
          OUTPUT_DOCX = REPORT_NAME + ".docx"
          CHART_IMAGE = REPORT_NAME + ".png"
      
          # Find the most recently modified XML file
          test_files = sorted(glob.glob(f"{XML_DIR}/**/*.xml", recursive=True), key=os.path.getmtime, reverse=True)
          if not test_files:
              print("No JUnit XML files found.")
              exit(1)
      
          # Initialize the monthly results
          monthly_suites = TestSuite(name="Monthly Test Suites")
          passed, failed, skipped = 0, 0, 0
          test_case_names = []
      
          for file in test_files:
              print(f"Processing: {file}")
              xml = JUnitXml.fromfile(file)
      
              for suite in xml:
                  for case in suite:
                      if os.path.abspath(file) == os.path.abspath(test_files[0]):
                          test_case_names.append(case.name)
      
                      monthly_suites.add_testcase(case)
      
                      if case.result:
                          if any(isinstance(r, (Failure, Error)) for r in case.result):
                              failed += 1
                          elif any(isinstance(r, Skipped) for r in case.result):
                              skipped += 1
                          else:
                              passed += 1
                      else:
                          passed += 1
      
          if passed + failed + skipped == 0:
              print("No test cases found. Skipping report generation.")
              exit(0)
      
          statuses = ["Passed", "Failed", "Skipped"]
          counts = [passed, failed, skipped]
          colors = ['green', 'red', 'gray']
      
          fig = go.Figure(go.Bar(
              x=counts,
              y=statuses,
              orientation='h',
              marker_color=colors,
              text=counts,
              textposition='outside'
          ))
      
          fig.update_layout(
              title="Test Status Breakdown (Monthly Test Results)",
              xaxis_title="Number of Tests",
              yaxis_title="Test Status",
              xaxis=dict(
                  showticklabels=False  # <- hides the numbers on x-axis
              ),
              margin=dict(l=100, r=20, t=50, b=50),
              height=400
          )
      
          # Save the chart as PNG image
          fig.write_image(CHART_IMAGE)
      
          # Create Word document
          doc = Document()
          doc.add_heading('Test Report: ' + REPORT_NAME, level=1)
          doc.add_paragraph(f"Passed: {passed}, Failed: {failed}, Skipped: {skipped}")
          doc.add_picture(CHART_IMAGE, width=Inches(5.5))
          doc.add_paragraph()
          doc.add_heading("Test Cases Executed", level=2)
      
          for name in test_case_names:
            p = doc.add_paragraph(name, style='List Bullet')
            for run in p.runs:
                run.font.size = Pt(8)
      
          doc.save(OUTPUT_DOCX)
          print(f"Word report saved as: {OUTPUT_DOCX}")
          EOF
      
      - name: Upload Word Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-docx
          path: ${{ github.event.inputs.workflow_name }} Test Report.docx

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "CI Test Report - ${{ github.event.inputs.workflow_name }}"
          body: "Tests have completed for '${{ github.event.inputs.workflow_name }}'. See attached report."
          to: michael.naguit@technocrat.com.au
          from: GitHub Actions <${{ secrets.SMTP_USER }}>
          attachments: |
            ${{ github.event.inputs.workflow_name }} Test Report.docx
