name: Run BugBug - QAO Production Suite

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'  # Runs daily at 7:00 AM Brisbane time (UTC+10)

jobs:
  run-bugbug-tests:
    runs-on: ubuntu-latest
    name: Run BugBug Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run QAO Production Suite
        id: run-bugbug-tests
        uses: bugbug-io/bugbug-github-action@v1.2.1
        continue-on-error: true
        with:
          apiToken: ${{ secrets.BUGBUG_API_TOKEN }}
          suiteId: 3a59a4a0-0397-4e45-9bef-b3f5acc0d6c8
          outputPath: test-results-${{ github.run_id }}.xml

      - name: Remove duplicate test cases from XML
        run: |
          python3 - <<EOF
          import xml.etree.ElementTree as ET
      
          file_path = "test-results-${{ github.run_id }}.xml"
          tree = ET.parse(file_path)
          root = tree.getroot()
      
          seen = set()
          for testsuite in root.findall("testsuite"):
              testcases = testsuite.findall("testcase")
              unique_cases = []
              for tc in testcases:
                  key = (tc.attrib.get("name"), tc.attrib.get("classname"))
                  if key not in seen:
                      seen.add(key)
                      unique_cases.append(tc)
              # Clear and repopulate testcases
              for tc in testcases:
                  testsuite.remove(tc)
              for tc in unique_cases:
                  testsuite.append(tc)
              # Update test count
              testsuite.set("tests", str(len(unique_cases)))
      
          tree.write(file_path, encoding="utf-8", xml_declaration=True)
          EOF
      
      - name: Getting Run Output
        run: |
          echo "Suite Run ID: ${{ steps.run-bugbug-tests.outputs.suiteRunId }}"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: bugbug-test-results-${{ github.run_id }}
          path: test-results-${{ github.run_id }}.xml

      - name: Fail workflow if tests failed
        if: steps.run-bugbug-tests.outcome == 'failure'
        run: |
          echo "BugBug test suite failed, marking workflow as failed."
          exit 1
